name: linting-formatting
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.13

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          black: true
          pylint: true